### ISSUE TITLE
There is no folder /etc/docker/ during containerd installation

### ISSUE THREAD

**Issue by pocake-svn** [jmutai/k8s-pre-bootstrap#7]
Error when processing setup_containerd.yml: there is no on host folder and file below
#- name: Set cgroup driver as systemd
#  ansible.builtin.template:
#    src: daemon.json.j2
#    dest: /etc/docker/daemon.json

**Comment by farconada** [comment]
easy fix for this: 
replace that task with this one:
```
- name: Set cgroup driver as systemd
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: SystemdCgroup = 
    line: SystemdCgroup = true
```

**Comment by yasinmkarya** [comment]
@farconada Thanks..

I try add some lines here:

```
- name: Set cgroup driver as systemd
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: SystemdCgroup = false
    line: SystemdCgroup = true
    state: present
    backup: yes
```
